apiVersion: v1
kind: Service
metadata:
  name: insurance-rag-app-service
spec:
  type: NodePort
  selector:
    app: insurance-rag-app
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP